version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
